baseurl: /cs224w-notes
title: Course on Machine Learning with Graphs
subtitle: Lecture Notes for Stanford CS224W.
simple_search: http://google.com/search
description: Lecture Notes for Stanford CS224W.
name: cs224w-notes
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
permalink: /articles/:short_year/:title
timezone: America/Los_Angeles
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
transfer:
  command: rsync
  settings: -av
  source: _site/

theme: jekyll-theme-cayman